server:
  port: 8113

spring:
  application:
    name: zeriter-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081//eureka/
#      defaultZone: http://39.97.223.51/:8081/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  config=: logback-spring.xml
zuul:
  ignored-services: "*"
  routes:
    base:
      serviceId: zeriter-base
      path: /base/**
  prefix: /zeriter

